<?php


/**
 * Skeleton subclass for representing a row from the 'author' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/18/10 00:49:25
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Author extends BaseAuthor {

} // Author

sfPropelBehavior::add('Author', array('changelog'));